"""initial schema

Revision ID: 8b972fb39ea9
Revises: 
Create Date: 2026-04-13 20:15:01.182359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b972fb39ea9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.Enum('SERVICE_TOGGLE', 'TASK_RUN', name='backgroundjobtype'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELED', name='backgroundjobstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('claimed_by', sa.String(length=120), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_dedupe_key'), ['dedupe_key'], unique=False)

    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('radarr_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('tmdb_title', sa.String(length=512), nullable=True),
    sa.Column('original_title', sa.String(length=512), nullable=True),
    sa.Column('tmdb_release_date', sa.DateTime(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('homepage', sa.String(length=500), nullable=True),
    sa.Column('origin_country', sa.JSON(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('backdrop_url', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('never_watched', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('last_metadata_refresh_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_imdb_id'), ['imdb_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_movies_radarr_id'), ['radarr_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_movies_tmdb_id'), ['tmdb_id'], unique=True)

    op.create_table('reclaim_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.Enum('MOVIE', 'SERIES', name='mediatype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('library_ids', sa.JSON(), nullable=True),
    sa.Column('min_popularity', sa.Float(), nullable=True),
    sa.Column('max_popularity', sa.Float(), nullable=True),
    sa.Column('min_vote_average', sa.Float(), nullable=True),
    sa.Column('max_vote_average', sa.Float(), nullable=True),
    sa.Column('min_vote_count', sa.Integer(), nullable=True),
    sa.Column('max_vote_count', sa.Integer(), nullable=True),
    sa.Column('min_view_count', sa.Integer(), nullable=True),
    sa.Column('max_view_count', sa.Integer(), nullable=True),
    sa.Column('include_never_watched', sa.Boolean(), nullable=False),
    sa.Column('min_days_since_added', sa.Integer(), nullable=True),
    sa.Column('max_days_since_added', sa.Integer(), nullable=True),
    sa.Column('min_days_since_last_watched', sa.Integer(), nullable=True),
    sa.Column('max_days_since_last_watched', sa.Integer(), nullable=True),
    sa.Column('min_size', sa.Integer(), nullable=True),
    sa.Column('max_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('sonarr_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('tvdb_id', sa.String(length=20), nullable=True),
    sa.Column('tmdb_title', sa.String(length=512), nullable=True),
    sa.Column('original_title', sa.String(length=512), nullable=True),
    sa.Column('tmdb_first_air_date', sa.DateTime(), nullable=True),
    sa.Column('tmdb_last_air_date', sa.DateTime(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('homepage', sa.String(length=500), nullable=True),
    sa.Column('origin_country', sa.JSON(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('backdrop_url', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('season_count', sa.Integer(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('never_watched', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('last_metadata_refresh_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_imdb_id'), ['imdb_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_series_sonarr_id'), ['sonarr_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_series_tmdb_id'), ['tmdb_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_series_tvdb_id'), ['tvdb_id'], unique=True)

    op.create_table('service_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_type', sa.Enum('SONARR', 'RADARR', 'JELLYFIN', 'PLEX', 'SEERR', name='service'), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_type')
    )
    op.create_table('service_media_libraries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('library_id', sa.String(length=50), nullable=False),
    sa.Column('library_name', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.Enum('MOVIE', 'SERIES', name='mediatype'), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task', sa.Enum('SYNC_MEDIA', 'RESYNC_MEDIA', 'SYNC_MEDIA_LIBRARIES', 'SYNC_LINKED_DATA', 'SCAN_CLEANUP_CANDIDATES', 'TAG_CLEANUP_CANDIDATES', 'DELETE_CLEANUP_CANDIDATES', 'WEEKLY_HOUSE_KEEPING', name='task'), nullable=False),
    sa.Column('schedule_type', sa.Enum('INTERVAL', 'CRON', 'MANUAL', name='scheduletype'), nullable=False),
    sa.Column('schedule_value', sa.String(length=100), nullable=False),
    sa.Column('default_schedule_type', sa.Enum('INTERVAL', 'CRON', 'MANUAL', name='scheduletype'), nullable=False),
    sa.Column('default_schedule_value', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('require_password_change', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('general_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auto_tag_enabled', sa.Boolean(), nullable=False),
    sa.Column('cleanup_tag_suffix', sa.String(length=15), nullable=False),
    sa.Column('worker_poll_min_seconds', sa.Float(), nullable=True),
    sa.Column('worker_poll_max_seconds', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Enum('SONARR', 'RADARR', 'JELLYFIN', 'PLEX', 'SEERR', name='service'), nullable=False),
    sa.Column('service_item_id', sa.String(length=100), nullable=False),
    sa.Column('service_media_id', sa.String(length=100), nullable=False),
    sa.Column('library_id', sa.String(length=100), nullable=False),
    sa.Column('library_name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('container', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'service', 'service_media_id', name='uq_movie_version')
    )
    with op.batch_alter_table('movie_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_versions_movie_id'), ['movie_id'], unique=False)

    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('new_cleanup_candidates', sa.Boolean(), nullable=False),
    sa.Column('request_approved', sa.Boolean(), nullable=False),
    sa.Column('request_declined', sa.Boolean(), nullable=False),
    sa.Column('admin_message', sa.Boolean(), nullable=False),
    sa.Column('task_failure', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.SmallInteger(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('never_watched', sa.Boolean(), nullable=True),
    sa.Column('air_date', sa.DateTime(), nullable=True),
    sa.Column('jellyfin_season_id', sa.String(length=100), nullable=True),
    sa.Column('plex_season_rating_key', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'season_number', name='uq_season_series_number')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_series_id'), ['series_id'], unique=False)

    op.create_table('series_service_refs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Enum('SONARR', 'RADARR', 'JELLYFIN', 'PLEX', 'SEERR', name='service'), nullable=False),
    sa.Column('service_id', sa.String(length=100), nullable=False),
    sa.Column('library_id', sa.String(length=100), nullable=False),
    sa.Column('library_name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'service', name='uq_series_service_ref')
    )
    with op.batch_alter_table('series_service_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_service_refs_series_id'), ['series_id'], unique=False)

    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.Enum('SYNC_MEDIA', 'RESYNC_MEDIA', 'SYNC_MEDIA_LIBRARIES', 'SYNC_LINKED_DATA', 'SCAN_CLEANUP_CANDIDATES', 'TAG_CLEANUP_CANDIDATES', 'DELETE_CLEANUP_CANDIDATES', 'WEEKLY_HOUSE_KEEPING', name='task'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'QUEUED', 'COMPLETED', 'ERROR', 'RUNNING', 'DISABLED', name='taskstatus'), nullable=False),
    sa.Column('task_schedule_id', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_schedule_id'], ['task_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protected_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_type', sa.Enum('MOVIE', 'SERIES', name='mediatype'), nullable=False),
    sa.Column('protected_by_user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('permanent', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['protected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protected_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protected_media_season_id'), ['season_id'], unique=False)

    op.create_table('reclaim_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_type', sa.Enum('MOVIE', 'SERIES', name='mediatype'), nullable=False),
    sa.Column('matched_rule_ids', sa.JSON(), nullable=False),
    sa.Column('matched_criteria', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('approved_for_deletion', sa.Boolean(), nullable=False),
    sa.Column('tagged_in_arr', sa.Boolean(), nullable=False),
    sa.Column('estimated_space_gb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reclaim_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reclaim_candidates_season_id'), ['season_id'], unique=False)

    op.create_table('protection_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_type', sa.Enum('MOVIE', 'SERIES', name='mediatype'), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_expires_at', sa.DateTime(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='protectionrequeststatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['reclaim_candidates.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protection_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protection_requests_season_id'), ['season_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protection_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protection_requests_season_id'))

    op.drop_table('protection_requests')
    with op.batch_alter_table('reclaim_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reclaim_candidates_season_id'))

    op.drop_table('reclaim_candidates')
    with op.batch_alter_table('protected_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protected_media_season_id'))

    op.drop_table('protected_media')
    op.drop_table('task_runs')
    with op.batch_alter_table('series_service_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_service_refs_series_id'))

    op.drop_table('series_service_refs')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_series_id'))

    op.drop_table('seasons')
    op.drop_table('notification_settings')
    with op.batch_alter_table('movie_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_versions_movie_id'))

    op.drop_table('movie_versions')
    op.drop_table('general_settings')
    op.drop_table('users')
    op.drop_table('task_schedules')
    op.drop_table('service_media_libraries')
    op.drop_table('service_configs')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_tvdb_id'))
        batch_op.drop_index(batch_op.f('ix_series_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_series_sonarr_id'))
        batch_op.drop_index(batch_op.f('ix_series_imdb_id'))

    op.drop_table('series')
    op.drop_table('reclaim_rules')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_movies_radarr_id'))
        batch_op.drop_index(batch_op.f('ix_movies_imdb_id'))

    op.drop_table('movies')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_dedupe_key'))

    op.drop_table('background_jobs')
    # ### end Alembic commands ###
